-- ========================================
-- 01. COMPLETE DATABASE SETUP (VERSÃO FINAL)
-- ========================================

-- 1. Limpar banco atual completamente para evitar conflitos
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS ads CASCADE;
DROP TABLE IF EXISTS posts CASCADE;

-- 2. Criar tabelas com todas as colunas corretas
CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    excerpt TEXT,
    content TEXT,
    featured BOOLEAN DEFAULT FALSE,
    status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
    category VARCHAR(50) NOT NULL, -- Sem restrição (aceita qualquer categoria do React)
    tags TEXT[] DEFAULT '{}',      -- Coluna de tags para evitar o erro PGRST204
    author VARCHAR(100) NOT NULL,
    date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    image VARCHAR(500),            -- Coluna para a URL da imagem
    meta_title VARCHAR(255),
    meta_description TEXT,
    meta_keywords TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT REFERENCES posts(id) ON DELETE CASCADE,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(255) NOT NULL,
    content TEXT NOT NULL,
    status VARCHAR(20) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected')),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE ads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    content TEXT,
    category VARCHAR(50) NOT NULL CHECK (category IN ('banner', 'sidebar', 'footer', 'popup')),
    status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'approved')),
    image_url VARCHAR(500),
    link_url VARCHAR(500),
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Criar Índices de performance
CREATE INDEX idx_posts_status ON posts(status);
CREATE INDEX idx_posts_category ON posts(category);
CREATE INDEX idx_posts_date ON posts(date);
CREATE INDEX idx_posts_featured ON posts(featured);
CREATE INDEX idx_comments_post_id ON comments(post_id);
CREATE INDEX idx_comments_status ON comments(status);
CREATE INDEX idx_ads_status ON ads(status);
CREATE INDEX idx_ads_category ON ads(category);

-- 4. Função de Slug e Triggers de Data de Atualização (updated_at)
CREATE OR REPLACE FUNCTION generate_slug(title TEXT) RETURNS TEXT AS $$
BEGIN
    RETURN lower(regexp_replace(regexp_replace(unaccent(title), '[^a-zA-Z0-9\s-]', '', 'g'), '\s+', '-', 'g'));
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_posts_updated_at BEFORE UPDATE ON posts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_comments_updated_at BEFORE UPDATE ON comments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_ads_updated_at BEFORE UPDATE ON ads FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 5. Inserir Dados de Exemplo - Matérias (Com imagens reais)
INSERT INTO posts (title, slug, excerpt, content, featured, status, category, tags, author, date, image, meta_title, meta_description, meta_keywords) VALUES
('Governo anuncia novo programa de desenvolvimento econômico para SC', 'governo-anuncia-novo-programa-desenvolvimento-economico-sc', 
'O governo estadual lançou hoje um programa inovador para impulsionar a economia de Santa Catarina, com investimentos de R$ 2 bilhões em diversos setores.',
'O governador de Santa Catarina anunciou nesta terça-feira um programa abrangente de desenvolvimento econômico que promete transformar o cenário empresarial do estado. O programa "SC em Movimento" contará com investimentos recordes de R$ 2 bilhões distribuídos ao longo dos próximos três anos.',
true, 'published', 'Economia', '{"economia", "governo", "sc"}', 'Maria Silva', '2024-01-15 10:00:00', 
'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80',
'Governo anuncia programa de desenvolvimento econômico para SC',
'O governo de Santa Catarina lançou programa com R$ 2 bilhões para impulsionar a economia do estado.',
'economia, santa catarina, governo, desenvolvimento, investimento'),

('Prefeitura de Florianópolis inicia obras de mobilidade urbana', 'prefeitura-florianopolis-inicia-obras-mobilidade-urbana',
'Novas ciclovias e corredores de ônibus serão implementados para melhorar o transporte na capital catarinense.',
'A prefeitura de Florianópolis deu início esta semana às obras do maior projeto de mobilidade urbana dos últimos dez anos. O investimento de R$ 150 milhões vai transformar o sistema de transporte da cidade.',
true, 'published', 'Sociedade', '{"mobilidade", "florianópolis", "obras"}', 'João Santos', '2024-01-14 14:30:00',
'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=800&q=80',
'Prefeitura de Florianópolis inicia obras de mobilidade urbana',
'Novas ciclovias e corredores de ônibus serão implementados em Florianópolis com investimento de R$ 150 milhões.',
'mobilidade urbana, florianópolis, transporte, ciclovias, obras'),

('Universidade Federal de SC desenvolve pesquisa inovadora em energia solar', 'universidade-federal-sc-desenvolve-pesquisa-inovadora-energia-solar',
'Pesquisadores criam nova tecnologia que aumenta em 40% a eficiência de painéis solares, prometendo revolução no setor energético.',
'Uma equipe de pesquisadores da Universidade Federal de Santa Catarina (UFSC) desenvolveu uma tecnologia inovadora que pode revolucionar o mercado de energia solar. O novo sistema aumenta em 40% a eficiência dos painéis fotovoltaicos.',
false, 'published', 'Tecnologia', '{"energia", "ufsc", "pesquisa"}', 'Ana Costa', '2024-01-13 09:15:00',
'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80',
'UFSC desenvolve pesquisa inovadora em energia solar',
'Pesquisadores da UFSC criam tecnologia que aumenta em 40% a eficiência de painéis solares.',
'energia solar, ufsc, pesquisa, tecnologia, inovação'),

('Festival de Cinema de SC anuncia programação completa para 2024', 'festival-cinema-sc-anuncia-programacao-completa-2024',
'Evento vai contar com mais de 200 filmes de 30 países diferentes, incluindo estreias mundiais e retrospectivas de grandes diretores.',
'O Festival de Cinema de Santa Catarina anunciou hoje sua programação completa para a edição de 2024, que promete ser a maior da história do evento. Com mais de 200 filmes de 30 países, o festival vai acontecer em Florianópolis de 15 a 25 de março.',
false, 'published', 'Cultura', '{"cinema", "festival", "cultura"}', 'Pedro Oliveira', '2024-01-12 16:45:00',
'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&q=80',
'Festival de Cinema de SC anuncia programação para 2024',
'Festival vai exibir mais de 200 filmes de 30 países em Florianópolis de 15 a 25 de março.',
'festival de cinema, santa catarina, programação, filmes, cultura'),

('Santa Catarina bate recorde de exportações em 2023', 'santa-catarina-bate-recorde-exportacoes-2023',
'Estado exportou US$ 15,8 bilhões no ano passado, crescimento de 12% em relação a 2022, aponta dados da FIESC.',
'Santa Catarina bateu recorde histórico de exportações em 2023, alcançando US$ 15,8 bilhões, representando um crescimento de 12% em relação ao ano anterior. Os dados foram divulgados hoje pela Federação das Indústrias do Estado de Santa Catarina (FIESC).',
true, 'published', 'Economia', '{"exportação", "fiesc", "economia"}', 'Carlos Mendes', '2024-01-11 11:20:00',
'https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?w=800&q=80',
'Santa Catarina bate recorde de exportações em 2023',
'Estado exportou US$ 15,8 bilhões em 2023, crescimento de 12% em relação a 2022.',
'exportações, santa catarina, fiesc, economia, recorde');

-- 6. Inserir Dados de Exemplo - Anúncios (Com imagens reais)
INSERT INTO ads (title, slug, content, category, status, image_url, link_url, start_date, end_date) VALUES
('Promoção de Verão - Lojas ABC', 'promocao-verao-lojas-abc', 
'Grandes ofertas em toda a linha de verão. Até 70% OFF em produtos selecionados.', 'banner', 'approved',
'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80',
'https://lojasabc.com.br/promocoes', '2024-01-01 00:00:00', '2024-02-29 23:59:59'),

('Supermercado Preço Bom - Semanal', 'supermercado-preco-bom-semanal',
'Ofertas da semana em frutas, legumes e produtos de limpeza. Confira!', 'sidebar', 'approved',
'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80',
'https://precobom.com.br/ofertas', '2024-01-15 00:00:00', '2024-01-21 23:59:59'),

('Concessionária SC Motors - Ano Novo', 'concessionaria-sc-motors-ano-novo',
'Veículos 0km com condições especiais para começar o ano. Parcele em até 60x.', 'footer', 'approved',
'https://images.unsplash.com/photo-1563720225384-9a0279c13b2c?w=800&q=80',
'https://scmotors.com.br/promocoes', '2024-01-01 00:00:00', '2024-01-31 23:59:59');

-- 7. Força atualização do schema para as APIs reconhecerem as mudanças (evita erros PGRST)
NOTIFY pgrst, 'reload schema';