-- ========================================
-- 01_DATABASE_SETUP.sql
-- ========================================
-- Complete database setup for Opine Agora SC
-- Execute this FIRST in your Supabase SQL Editor

-- 1. Drop existing tables to avoid conflicts
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS ads CASCADE;
DROP TABLE IF EXISTS posts CASCADE;

-- 2. Create posts table
CREATE TABLE posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    excerpt TEXT,
    content TEXT,
    featured BOOLEAN DEFAULT FALSE,
    status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'published')),
    category VARCHAR(50) NOT NULL,
    tags TEXT[] DEFAULT '{}',
    author VARCHAR(100) NOT NULL,
    date TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    image VARCHAR(500),
    meta_title VARCHAR(255),
    meta_description TEXT,
    meta_keywords TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 3. Create comments table
CREATE TABLE public.comments (
  id bigint generated by default as identity not null,
  post_id bigint null,
  name character varying(100) not null,
  email character varying(255) not null,
  content text not null,
  status character varying(20) null default 'pending'::character varying,
  created_at timestamp with time zone null default CURRENT_TIMESTAMP,
  updated_at timestamp with time zone null default CURRENT_TIMESTAMP,
  constraint comments_pkey primary key (id),
  constraint comments_email_time_unique unique (email, post_id, created_at),
  constraint comments_post_id_fkey foreign KEY (post_id) references posts (id) on delete CASCADE,
  constraint comments_status_check check (
    (
      (status)::text = any (
        (
          array[
            'pending'::character varying,
            'approved'::character varying,
            'rejected'::character varying
          ]
        )::text[]
      )
    )
  )
) TABLESPACE pg_default;

-- 4. Create ads table
CREATE TABLE ads (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) UNIQUE NOT NULL,
    content TEXT,
    category VARCHAR(50) NOT NULL CHECK (category IN ('banner', 'sidebar', 'footer', 'popup')),
    status VARCHAR(20) DEFAULT 'draft' CHECK (status IN ('draft', 'approved')),
    image_url VARCHAR(500),
    link_url VARCHAR(500),
    start_date TIMESTAMP WITH TIME ZONE,
    end_date TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- 5. Create performance indexes
CREATE INDEX IF NOT EXISTS idx_posts_status ON public.posts using btree (status) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_posts_category ON public.posts using btree (category) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_posts_date ON public.posts using btree (date) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_posts_featured ON public.posts using btree (featured) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_comments_post_id ON public.comments using btree (post_id) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_comments_status ON public.comments using btree (status) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_comments_email ON public.comments using btree (email) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_comments_created_at ON public.comments using btree (created_at) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_ads_status ON public.ads using btree (status) TABLESPACE pg_default;
CREATE INDEX IF NOT EXISTS idx_ads_category ON public.ads using btree (category) TABLESPACE pg_default;

-- 6. Create utility functions
CREATE OR REPLACE FUNCTION generate_slug(title TEXT) RETURNS TEXT AS $$
BEGIN
    RETURN lower(regexp_replace(regexp_replace(unaccent(title), '[^a-zA-Z0-9\s-]', '', 'g'), '\s+', '-', 'g'));
END;
$$ LANGUAGE plpgsql;

CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- 7. Create triggers for updated_at
CREATE TRIGGER update_posts_updated_at BEFORE UPDATE ON posts FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_comments_updated_at BEFORE UPDATE ON comments FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
CREATE TRIGGER update_ads_updated_at BEFORE UPDATE ON ads FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

-- 8. Insert sample data - Posts
INSERT INTO posts (
    id, title, slug, excerpt, content, featured, status, category, 
    author, date, image, meta_title, meta_description, meta_keywords, 
    created_at, updated_at, tags
) VALUES 
('11', 'Governo anuncia novo programa de desenvolvimento econômico para SC', 'governo-anuncia-novo-programa-desenvolvimento-economico-sc', 'O governo estadual lançou hoje um programa inovador para impulsionar a economia de Santa Catarina, com investimentos de R$ 2 bilhões em diversos setores.', '[{"id":"block_1771229449405","type":"text","data":{"content":"A parceria entre o Governo do Estado e o setor produtivo continua promovendo mais competitividade à indústria e novas oportunidades aos catarinenses. Nesta quarta-feira, 5, o governador Jorginho Mello assinou 30 novos contratos dos programas Prodec, Pró-Emprego e Tratamento Tributário Diferenciado 489 (TTD 489). Os projetos contemplados somam R$ 1,2 bilhão em investimentos privados em todas as regiões do Estado e vão gerar cerca de 4,2 mil empregos diretos e indiretos até 2028.\n\nO ato foi realizado na Casa d’Agronômica, em Florianópolis, com a participação da vice-governadora Marilisa Boehm, além dos secretários Cleverson Siewert (Fazenda) e Silvio Dreveck (Indústria, Comércio e Serviços). A programação também reuniu lideranças políticas, dirigentes de associações, federações industriais e representantes das empresas contempladas.\n\nCom a nova rodada, o balanço geral dos programas entre 2023 e 2025 chega a 435 projetos aprovados, representando R$ 30 bilhões em investimentos privados e mais de 110 mil empregos diretos e indiretos — números que reforçam o dinamismo e a confiança do setor produtivo em Santa Catarina.\n\n\nTRATAMENTO TRIBUTÁRIO DIFERENCIADO 489\n\nTem como objetivo autorizar limites adicionais para a transferência de créditos acumulados de ICMS decorrentes de operações ou prestações destinadas ao exterior, isentas ou diferidas."}}]', true, 'published', 'Economia', 'Maria Silva', '2024-01-15 10:00:00+00', 'https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=800&q=80', 'Governo anuncia programa de desenvolvimento econômico para SC', 'O governo de Santa Catarina lançou programa com R$ 2 bilhões para impulsionar a economia do estado.', 'economia, santa catarina, governo, desenvolvimento, investimento', '2026-02-16 01:06:31.55959+00', '2026-02-16 08:54:02.92735+00', ARRAY['economia','governo','sc']),

('12', 'Prefeitura de Florianópolis inicia obras de mobilidade urbana', 'prefeitura-florianopolis-inicia-obras-mobilidade-urbana', 'Novas ciclovias e corredores de ônibus serão implementados para melhorar o transporte na capital catarinense.', 'A prefeitura de Florianópolis deu início esta semana às obras do maior projeto de mobilidade urbana dos últimos dez anos. O investimento de R$ 150 milhões vai transformar o sistema de transporte da cidade.', true, 'published', 'Sociedade', 'João Santos', '2024-01-14 14:30:00+00', 'https://images.unsplash.com/photo-1515162816999-a0c47dc192f7?w=800&q=80', 'Prefeitura de Florianópolis inicia obras de mobilidade urbana', 'Novas ciclovias e corredores de ônibus serão implementados em Florianópolis com investimento de R$ 150 milhões.', 'mobilidade urbana, florianópolis, transporte, ciclovias, obras', '2026-02-16 01:06:31.55959+00', '2026-02-16 01:06:31.55959+00', ARRAY['mobilidade','florianópolis','obras']),

('13', 'Universidade Federal de SC desenvolve pesquisa inovadora em energia solar', 'universidade-federal-sc-desenvolve-pesquisa-innovadora-energia-solar', 'Pesquisadores criam nova tecnologia que aumenta em 40% a eficiência de painéis solares, prometendo revolução no setor energético.', '[{"id":"block_1771231394495","type":"imageLink","data":{"imageUrl":"","linkUrl":"","alt":"","caption":"","showOverlay":true}},{"id":"block_1771231643442","type":"imagemComLink","data":{"imageUrl":"https://res.cloudinary.com/dhalhzqo7/image/upload/v1771231682/opine-agora/oct8ivpv3sc9thdptnyu.jpg","linkUrl":"https://linkedin.com/in/pedroalves0","alt":"Banner: Faço seu site pra você","caption":"Entre em contato e me diga que site você deseja!","showOverlay":true}}]', false, 'published', 'Tecnologia', 'Ana Costa', '2024-01-13 09:15:00+00', 'https://images.unsplash.com/photo-1509391366360-2e959784a276?w=800&q=80', 'UFSC desenvolve pesquisa inovadora em energia solar', 'Pesquisadores da UFSC criam tecnologia que aumenta em 40% a eficiência de painéis solares.', 'energia solar, ufsc, pesquisa, tecnologia, inovação', '2026-02-16 01:06:31.55959+00', '2026-02-16 08:52:57.399384+00', ARRAY['energia','ufsc','pesquisa']),

('14', 'Festival de Cinema de SC anuncia programação completa para 2024', 'festival-cinema-sc-anuncia-programacao-completa-2024', 'Evento vai contar com mais de 200 filmes de 30 países diferentes, incluindo estreias mundiais e retrospectivas de grandes diretores.', 'O Festival de Cinema de Santa Catarina anunciou hoje sua programação completa para a edição de 2024, que promete ser a maior da história do evento. Com mais de 200 filmes de 30 países, o festival vai acontecer em Florianópolis de 15 a 25 de março.', false, 'published', 'Cultura', 'Pedro Oliveira', '2024-01-12 16:45:00+00', 'https://images.unsplash.com/photo-1485846234645-a62644f84728?w=800&q=80', 'Festival de Cinema de SC anuncia programação para 2024', 'Festival vai exibir mais de 200 filmes de 30 países em Florianópolis de 15 a 25 de março.', 'festival de cinema, santa catarina, programação, filmes, cultura', '2026-02-16 01:06:31.55959+00', '2026-02-16 01:06:31.55959+00', ARRAY['cinema','festival','cultura']),

('15', 'Santa Catarina bate recorde de exportações em 2023', 'santa-catarina-bate-recorde-exportacoes-2023', 'Estado exportou US$ 15,8 bilhões no ano passado, crescimento de 12% em relação a 2022, aponta dados da FIESC.', 'Santa Catarina bateu recorde histórico de exportações em 2023, alcançando US$ 15,8 bilhões, representando um crescimento de 12% em relação ao ano anterior. Os dados foram divulgados hoje pela Federação das Indústrias do Estado de Santa Catarina (FIESC).', true, 'published', 'Economia', 'Carlos Mendes', '2024-01-11 11:20:00+00', 'https://images.unsplash.com/photo-1494412574643-ff11b0a5c1c3?w=800&q=80', 'Santa Catarina bate recorde de exportações em 2023', 'Estado exportou US$ 15,8 bilhões em 2023, crescimento de 12% em relação a 2022.', 'exportações, santa catarina, fiesc, economia, recorde', '2026-02-16 01:06:31.55959+00', '2026-02-16 01:06:31.55959+00', ARRAY['exportação','fiesc','economia']),

('16', 'Novo hospital infantil será construído na Grande Florianópolis', 'novo-hospital-infantil-sera-construido-grande-florianopolis', 'Governo estadual anuncia investimento de R$ 300 milhões para construção do maior hospital infantil da região Sul.', 'O governo de Santa Catarina anunciou hoje a construção do maior hospital infantil da região Sul, que será erguido na Grande Florianópolis. O investimento de R$ 300 milhões vai beneficiar mais de 500 mil crianças e adolescentes.', false, 'published', 'Saúde', 'Luiza Fernandes', '2024-01-10 08:30:00+00', 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?w=800&q=80', 'Novo hospital infantil será construído na Grande Florianópolis', 'Governo anuncia investimento de R$ 300 milhões para construção do maior hospital infantil da região Sul.', 'hospital infantil, saúde, grande florianópolis, investimento, governo', '2026-02-16 01:06:31.55959+00', '2026-02-16 01:06:31.55959+00', ARRAY['saúde','hospital','governo']),

('17', 'Times catarinenses se destacam no Campeonato Brasileiro', 'times-catarinenses-destacam-campeonato-brasileiro', 'Avaí, Figueirense e Chapecoense mostram força no início do campeonato, com resultados expressivos fora de casa.', '[{"id":"block_1771227976892","type":"video","data":{"videoUrl":"https://www.youtube.com/watch?v=511K1axmFkw","title":"Veja os melhores momentos:"}}]', false, 'published', 'Esportes', 'Ricardo Souza', '2024-01-09 20:00:00+00', 'https://images.unsplash.com/photo-1546717003-caee5f93a9db?fm=jpg&q=60&w=3000&auto=format&fit=crop&ixlib=rb-4.1.0&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D', 'Times catarinenses se destacam no Campeonato Brasileiro', 'Avaí, Figueirense e Chapecoense mostram força no início do campeonato brasileiro.', 'futebol, times catarinenses, campeonato brasileiro, avaí, figueirense, chapecoense', '2026-02-16 01:06:31.55959+00', '2026-02-16 07:46:40.704091+00', ARRAY['futebol','esportes','brasileirão']),

('18', 'Projeto de educação ambiental beneficia mais de 100 escolas em SC', 'projeto-educacao-ambiental-beneficia-100-escolas-sc', 'Iniciativa do governo estadual leva educação sustentável para estudantes de todo o estado, com foco em reciclagem e conservação.', 'Um projeto inovador de educação ambiental está transformando a realidade de mais de 100 escolas em Santa Catarina. A iniciativa do governo estadual leva educação sustentável para estudantes de todo o estado, com foco especial em reciclagem e conservação ambiental.', false, 'published', 'Educação', 'Mariana Costa', '2024-01-08 13:15:00+00', 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&q=80', 'Projeto de educação ambiental beneficia escolas em SC', 'Iniciativa leva educação sustentável para mais de 100 escolas em Santa Catarina.', 'educação ambiental, escolas, santa catarina, sustentabilidade, reciclagem', '2026-02-16 01:06:31.55959+00', '2026-02-16 01:06:31.55959+00', ARRAY['educação','meio ambiente','escolas']),

('19', 'Kafka Multimarcas - A sua pesquisa termina aqui!', 'kafka-multimarcas-a-sua-pesquisa-termina-aqui', 'O lugar certo para sair de carro novo! Dê uma olhada na mais nova revendedora de carros de Joinville que atrai muitos olhares desde sua inauguração.', '[{"id":"block_1771217661099","type":"text","data":{"content":"##Incrivelmente aqui em SC temos qualidade e preço baixo, confira:\n\nRecentemente em Joinville foi inaugurada a Kafka multimarkas, a melhor revendedora de automóveis de SC.\n\nA Kafka Multimarcas atua no mercado automobilístico, caracterizada por ser uma empresa sólida, de tradição, que conjuga excelência no atendimento e veículos com rigorosa qualidade, com o objetivo único de tornar real o sonho de cada cliente.\n\nApostando em confiança e credibilidade como princípios fundamentais de sua atuação, a empresa busca no mercado somente veículos diferenciados, através de um rigoroso critério técnico de avaliação que garante qualidade e procedência.\n\n"}},{"id":"block_1771218050028","type":"imageText","data":{"imageUrl":"https://kafkamultimarcas.com.br/foto-resize/X/1347524/1750/ford-ranger-xls-4x4-cd-diesel-aut.-2.0-2025-22806002.webp","alt":"Ford Ranger 2.0 XLS 4X4 CD DIESEL AUT. - 2025 - fonte: kafka website","text":"Ficou interessado?\n\nA loja oferece automóveis de diversas marcas, seminovos e zero quilômetro, nacionais e importados. Todos os veículos são criteriosamente testados e avaliados, característica que a revenda traz consigo até hoje e a diferencia no mercado. E é assim que a Kafka Multimarcas solidificou a sua marca, com uma conduta ética e respeito a seus clientes, parceiros e fornecedores.\n\nLá você encontra desde carros simples até carros de luxo, tudo com garantia e preço justo. Os vendedores têm sido muito elogiados pela sua boa vontade e desejo de ajudar. Conheça mais e veja por si só o que tem a dizer","align":"left"}},{"id":"block_1771217707124","type":"button","data":{"text":"Vá para o site","url":"https://kafkamultimarcas.com.br/","style":"primary"}},{"id":"block_1771217592099","type":"capa","data":{"title":"Kafka Multimarcas, a sua pesquisa termina AQUI!","imageUrl":"https://kafkamultimarcas.com.br/admin/uploads/banners/67d1d55eb39b8-12-03-25_15-41-34.png","alt":"Banner Kafka - fonte: site kafka multimarkas","showInBody":true}}]', false, 'draft', 'Economia', '', '2026-02-16 04:59:00.485+00', 'https://kafkamultimarcas.com.br/admin/uploads/banners/67d1d55eb39b8-12-03-25_15-41-34.png', NULL, NULL, NULL, '2026-02-16 04:59:01.967048+00', '2026-02-16 05:04:46.532667+00', ARRAY['Carros']),

('21', 'O que é API? Confira essa aula completa', 'o-que-e-api-confira-essa-aula-completa', 'Mundo do codigo, aprenda mais sobre programação com essa aula incrivel', '[{"id":"block_1771223387416","type":"video","data":{"videoUrl":"https://www.youtube.com/watch?v=ghTrp1x_1As","title":"Aprenda de uma vez por todas e não passe vergonha, veja:"}},{"id":"block_1771223530976","type":"button","data":{"text":"Saiba Mais","url":"https://developer.mozilla.org/en-US/docs/Web/API","style":"primary"}}]', true, 'published', 'Tecnologia', 'Pedro Moura', '2026-02-16 06:32:42.36+00', 'https://res.cloudinary.com/dhalhzqo7/image/upload/v1771223432/opine-agora/svl1wzlaci1i0gsaqd5k.png', NULL, NULL, NULL, '2026-02-16 06:32:43.847562+00', '2026-02-16 06:32:42.36+00', ARRAY['programação']),

('22', 'Wyse Systems - Chegaram para inovar', 'wyse-systems-chegaram-para-inovar', 'Chegou a hora de transformar sua frota para aumentar a satisfação dos motoristas, otimizar a utilização de todos os envolvidos e, claro, garantir entregas perfeitas.', '[{"id":"block_1771224671241","type":"button","data":{"text":"Saiba Mais","url":"https://www.wisesystems.com/about/","style":"secondary"}},{"id":"block_1771224696577","type":"imageText","data":{"imageUrl":"https://www.wisesystems.com/wp-content/uploads/2022/04/shutterstock_1619580013-scaled.jpg","alt":"Tecnologia move o mundo","text":"Nosso objetivo é otimizar suas operações de roteirização, onde as expectativas de clientes, destinatários, motoristas, despachantes e gerentes se encontram. Nossa equipe criou um sistema intuitivo, modular, de fácil integração e que comprovadamente proporciona tranquilidade em cada entrega.","align":"left"}},{"id":"block_1771224877257","type":"text","data":{"content":"O mecanismo de IA de alto desempenho da Wise Systems foi projetado para atender às suas entregas mais desafiadoras com eficiência, análises e uma interface intuitiva. \n\nSeus Clientes dizem:\n\n\"A entrega da última milha nos proporciona uma perspectiva única sobre a saúde e o funcionamento de uma cidade. Temos o privilégio de otimizar cada cidade em que a Wise Systems atua — com cada novo motorista, entrega e rota.\"\n\nChazz Sims\nFundador e CEO\n\n"}},{"id":"block_1771224993097","type":"ad","data":{"code":"<a href=\"https://www.squarespace.com/invoicing/?channel=display_nonprogrammatic&subchannel=unsplash&campaign=29090009&subcampaign=421545165_613965499&source=235629780&utm_medium=display_nonprogrammatic&utm_source=unsplash&\" target=\"_blank\">\n  <img src=\"https://images.unsplash.com/file-1747939393036-2c53a76c450aimage?w=416&dpr=2&auto=format&fit=crop&q=60\" alt=\"Banner\" />\n</a>","type":"banner"}}]', false, 'published', 'Tecnologia', '', '2026-02-16 07:03:35.481+00', 'https://www.wisesystems.com/wp-content/uploads/2022/06/N9A9692-1-scaled.jpg', NULL, NULL, NULL, '2026-02-16 07:03:37.203681+00', '2026-02-16 08:02:35.761191+00', ARRAY[]::TEXT[]),

('23', 'Confira os candidatos eleitos como vereadores de Concórdia', 'confira-os-candidatos-eleitos-como-vereadores-de-concordia', 'Foram definidos os 13 novos vereadores de Concórdia. O legislativo municipal teve apenas duas reeleições. Portanto, é uma das maiores renovações que a câmara já viu nos últimos pleitos.', '[{"id":"block_1771232557914","type":"carousel","data":{"images":[{"url":"https://www.portalconcordia.com.br/arquivos_personalizados/gera_foto/noticia_conteudo/arquivos_personalizados/uploads/noticias/fotos/88_68dd71abc6bbd.jpeg","alt":"Vereadores de Concordia","caption":"Foto: Imprensa Câmara Municipal de Concórdia","link":""},{"url":"https://www.portalconcordia.com.br/arquivos_personalizados/gera_foto/noticia_conteudo/arquivos_personalizados/uploads/noticias/fotos/42_68b6d74767f25.jpg","alt":"","caption":"Daisy Trombetta / Câmara de Vereadores","link":""},{"url":"https://www.portalconcordia.com.br/arquivos_personalizados/gera_foto/noticia_conteudo/arquivos_personalizados/uploads/noticias/fotos/23_677682d2ce372.jpg","alt":"","caption":"Foto: Lucas Villiger e Luis Longhini/ Rádios Rural/96","link":""}]}},{"id":"block_1771232976746","type":"text","data":{"content":"A Câmara de Vereadores de Concórdia deu início ao calendário de sessões ordinárias de 2025 nesta segunda-feira, 3 de fevereiro. O encontro marcou o primeiro compromisso oficial do novo Legislativo e foi conduzido pelo presidente Closmar Zagonel, que, apesar de estar em seu sexto mandato, assumiu a presidência da Casa pela primeira vez. Zagonel destacou a importância do momento e reafirmou o compromisso da Câmara em trabalhar pelo avanço do município.\n\nA nova composição da Câmara reflete uma significativa renovação política, com apenas dois vereadores reeleitos e 11 novos representantes.\n\nO prefeito Edilson Massocco e o vice-prefeito Fábio Ferri prestigiaram a sessão inaugural, fortalecendo o diálogo entre os poderes Executivo e Legislativo e demonstrando a disposição para um trabalho conjunto em prol da comunidade.\n\nDurante a sessão, diversos projetos deram entrada na Casa e devem ser analisados e votados ao longo da semana. Outro destaque da noite foi a eleição para o cargo de segundo secretário da Mesa Diretora. A vaga ficou em aberto após Rudimar Zanella, anteriormente eleito para a função, deixar a vereança para assumir o comando da Secretaria Municipal de Saúde. Em consenso, o nome do emedebista Honestino Malacarne foi escolhido para ocupar a cadeira.\n\nNesta primeira semana de atividades, a Câmara realizará mais três sessões, até a quinta-feira, dia 6 de fevereiro. Os encontros seguirão o horário tradicional, com início às 18h, e serão transmitidos ao vivo, garantindo transparência e acesso à população.\n"}},{"id":"block_1771233118418","type":"imagemComLink","data":{"imageUrl":"https://res.cloudinary.com/dhalhzqo7/image/upload/v1771233127/opine-agora/oqw3crs4mtfdo4lgzzni.png","linkUrl":"https://www.radiorural.com.br/noticias/61688-acic-concordia-manifesta-preocupacao-com-proposta-de-fim-da-escala-6x1","alt":"Banner anuncio","caption":"","showOverlay":true}}]', true, 'published', 'Política', '', '2026-02-16 09:12:32.747+00', 'https://www.portalconcordia.com.br/arquivos_personalizados/gera_foto/noticia_conteudo/arquivos_personalizados/uploads/biblioteca_imagens/02_66265bcb39902.jpg', NULL, NULL, NULL, '2026-02-16 09:12:33.282699+00', '2026-02-16 09:12:32.747+00', ARRAY[]::TEXT[]);

-- 9. Insert sample data - Ads
INSERT INTO ads (title, slug, content, category, status, image_url, link_url, start_date, end_date) VALUES
('Promoção de Verão - Lojas ABC', 'promocao-verao-lojas-abc', 
'Grandes ofertas em toda a linha de verão. Até 70% OFF em produtos selecionados.', 'banner', 'approved',
'https://images.unsplash.com/photo-1607082348824-0a96f2a4b9da?w=800&q=80',
'https://lojasabc.com.br/promocoes', '2024-01-01 00:00:00', '2024-02-29 23:59:59'),

('Supermercado Preço Bom - Semanal', 'supermercado-preco-bom-semanal',
'Ofertas da semana em frutas, legumes e produtos de limpeza. Confira!', 'sidebar', 'approved',
'https://images.unsplash.com/photo-1542838132-92c53300491e?w=800&q=80',
'https://precobom.com.br/ofertas', '2024-01-15 00:00:00', '2024-01-21 23:59:59'),

('Concessionária SC Motors - Ano Novo', 'concessionaria-sc-motors-ano-novo',
'Veículos 0km com condições especiais para começar o ano. Parcele em até 60x.', 'footer', 'approved',
'https://images.unsplash.com/photo-1563720225384-9a0279c13b2c?w=800&q=80',
'https://scmotors.com.br/promocoes', '2024-01-01 00:00:00', '2024-01-31 23:59:59');

-- 10. Refresh schema for Supabase APIs
NOTIFY pgrst, 'reload schema';

-- 11. Setup confirmation
DO $$
BEGIN
    RAISE NOTICE '=== DATABASE SETUP COMPLETED ===';
    RAISE NOTICE 'Tables: posts, comments, ads created successfully';
    RAISE NOTICE 'Sample data inserted';
    RAISE NOTICE 'Indexes and triggers created';
    RAISE NOTICE 'Next step: Run 02_SECURITY_SETUP.sql';
    RAISE NOTICE '=================================';
END $$;
