-- Criar tabela de newsletter subscriptions
CREATE TABLE newsletter_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE NOT NULL,
    status VARCHAR(20) DEFAULT 'active' CHECK (status IN ('active', 'inactive', 'unsubscribed')),
    ip_address INET, -- Para rate limiting
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Criar índice para busca por email
CREATE INDEX idx_newsletter_email ON newsletter_subscriptions(email);

-- Criar índice para busca por status
CREATE INDEX idx_newsletter_status ON newsletter_subscriptions(status);

-- Criar índice para rate limiting (IP + data)
CREATE INDEX idx_newsletter_ip_date ON newsletter_subscriptions(ip_address, created_at);

-- Inserir alguns dados de exemplo (opcional)
INSERT INTO newsletter_subscriptions (email, status, ip_address) VALUES
    ('joao.silva@example.com', 'active', '192.168.1.1'),
    ('maria.santos@example.com', 'active', '192.168.1.2'),
    ('pedro.oliveira@example.com', 'active', '192.168.1.3'),
    ('ana.costa@example.com', 'active', '192.168.1.4'),
    ('carlos.souza@example.com', 'active', '192.168.1.5');

-- RLS Policies para newsletter subscriptions
ALTER TABLE newsletter_subscriptions ENABLE ROW LEVEL SECURITY;

-- Policy para permitir leitura apenas para usuários autenticados
CREATE POLICY "Authenticated users can view newsletter subscriptions" ON newsletter_subscriptions
    FOR SELECT USING (auth.role() = 'authenticated');

-- Policy para permitir inserção (publico - newsletter signup) com validações básicas
CREATE POLICY "Anyone can insert newsletter subscriptions" ON newsletter_subscriptions
    FOR INSERT WITH CHECK (
        -- Email válido
        email ~* '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$'
    );

-- Policy para permitir atualização apenas para admins
CREATE POLICY "Admins can update newsletter subscriptions" ON newsletter_subscriptions
    FOR UPDATE USING (
        EXISTS (
            SELECT 1 FROM auth.users 
            WHERE auth.users.id = auth.uid() 
            AND auth.users.email = 'cristiano@opineagorasc.com.br'
        )
    );

-- Policy para permitir deleção apenas para admins
CREATE POLICY "Admins can delete newsletter subscriptions" ON newsletter_subscriptions
    FOR DELETE USING (
        EXISTS (
            SELECT 1 FROM auth.users 
            WHERE auth.users.id = auth.uid() 
            AND auth.users.email = 'cristiano@opineagorasc.com.br'
        )
    );

-- Function para obter IP do cliente (para rate limiting)
CREATE OR REPLACE FUNCTION get_client_ip()
RETURNS INET AS $$
BEGIN
    -- Tentar obter IP de várias fontes
    BEGIN
        RETURN current_setting('request.headers.x-forwarded-for', true)::inet;
    EXCEPTION WHEN OTHERS THEN
        BEGIN
            RETURN current_setting('request.headers.x-real-ip', true)::inet;
        EXCEPTION WHEN OTHERS THEN
            BEGIN
                RETURN inet_client_addr();
            EXCEPTION WHEN OTHERS THEN
                RETURN '127.0.0.1'::inet; -- Fallback
            END;
        END;
    END;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger para armazenar IP do cliente
CREATE OR REPLACE FUNCTION set_client_ip()
RETURNS TRIGGER AS $$
BEGIN
    -- Armazenar IP do cliente
    NEW.ip_address := get_client_ip();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger para capturar IP antes da inserção
CREATE TRIGGER newsletter_set_ip
    BEFORE INSERT ON newsletter_subscriptions
    FOR EACH ROW
    EXECUTE FUNCTION set_client_ip();

-- Function para verificar rate limit (chamada do frontend)
CREATE OR REPLACE FUNCTION check_newsletter_rate_limit(ip_param INET)
RETURNS BOOLEAN AS $$
DECLARE
    recent_count INTEGER;
BEGIN
    -- Verificar inscrições nas últimas 24 horas por IP
    SELECT COUNT(*) INTO recent_count
    FROM newsletter_subscriptions 
    WHERE ip_address = ip_param 
    AND created_at > NOW() - INTERVAL '24 hours';
    
    -- Se mais de 5 inscrições em 24 horas, bloquear
    IF recent_count >= 5 THEN
        RETURN FALSE;
    END IF;
    
    -- Verificar inscrições nas últimas 1 hora por IP
    SELECT COUNT(*) INTO recent_count
    FROM newsletter_subscriptions 
    WHERE ip_address = ip_param 
    AND created_at > NOW() - INTERVAL '1 hour';
    
    -- Se mais de 2 inscrições em 1 hora, bloquear
    IF recent_count >= 2 THEN
        RETURN FALSE;
    END IF;
    
    RETURN TRUE;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Function para verificar se email já existe
CREATE OR REPLACE FUNCTION check_email_exists(email_param VARCHAR)
RETURNS BOOLEAN AS $$
DECLARE
    email_count INTEGER;
BEGIN
    SELECT COUNT(*) INTO email_count
    FROM newsletter_subscriptions 
    WHERE email = email_param;
    
    RETURN email_count = 0;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;
